const Projects_data = [
    {
        id: 1,
        img: 'assets/PetCare.png',
        title: 'PetCare',
        topic: 'UI/UX',
        icon: 'assets/open.svg',
        link: 'https://xd.adobe.com/view/f1be1271-7b57-4a03-8127-781ed87b4167-a4ed/',
        desc: 'A WebApp for detecting dog breeds using CNN',
    },
    {
        id: 2,
        img: 'assets/Facial-Recog.png',
        title: 'Facial Recognition',
        topic: 'AI/ML',
        icon: 'assets/open.svg',
        link: 'https://github.com/aishaandatt/IIT-Internship',
        desc: 'Facial Recognition System using DL and One Shot Learning.',
    },
    {
        id: 3,
        img: 'assets/Locus.png',
        title: 'Locus',
        topic: 'WebDev',
        icon: 'assets/open.svg',
        link: 'https://github.com/aishaandatt/HackHarvard',
        desc: 'A Discord like platform for education built on Django',
    },
    {
        id: 4,
        img: 'assets/AD.png',
        title: 'Access Denied App',
        topic: 'UI/UX',
        icon: 'assets/open.svg',
        link: 'https://xd.adobe.com/view/3b637827-ab67-4b78-8801-630c765742c5-6e30/specs/',
        desc: 'A flagship Hackathon by IETE-ISF.',
    },
    {
        id: 5,
        img: 'assets/animal.png',
        title: 'Animal Classification',
        topic: 'AI/ML',
        icon: 'assets/open.svg',
        link: 'https://github.com/aishaandatt/WildHacks',
        desc: 'Animal Classification, Submitted to WildHacks Hackathon and Won.',
    },
    {
        id: 6,
        img: 'assets/traffic.png',
        title: 'Traffic Signs Detection',
        topic: 'AI/ML',
        icon: 'assets/open.svg',
        link: 'https://github.com/aishaandatt/Traffic_Signs_AI',
        desc: 'Traffic Signs Recognition that helps car cameras to detect traffic signs.',
    },
    {
        id: 7,
        img: 'assets/proshop.png',
        title: 'ProShop',
        topic: 'WebDev',
        icon: 'assets/open.svg',
        link: 'https://github.com/aishaandatt/Proshop-IPWT',
        desc: 'An E-Commerce Website built using MERN stack',
    },
]
export default Projects_data