name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger on changes to main

permissions:
  contents: write  # Required to push to gh-pages

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js (if needed)
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Adjust if you're using a specific version

      - name: Install dependencies and build
        run: |
          npm install
          npm run build  # Customize if your build script has a different name

      - name: Deploy to gh-pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./root  # Change this to your build output folder
          publish_branch: gh-pages
